create extension if not exists pg_trgm;

create table if not exists public.loovi_ressarcimento (
  id          bigint generated always as identity primary key,
  sheet       text,
  analista_tab text,
  ano         smallint,
  "arquivo_origem" text,
  "pessoa" text,
  "analise_detalhamento_sinistro_ressarcimento" text,
  "analise_cobertura_segurado" text,
  "analise_cobertura_terceiros" text,
  "identificacao_envolvidos_protocolo_segurado" text,
  "identificacao_envolvidos_placa_segurado" text,
  "identificacao_veiculo_cliente_chave_natural" text,
  "identificacao_veiculo_veiculo" text,
  "analise_franquia_fipe_grupo_titular_crlv" text,
  "analise_franquia_fipe_grupo_fipe_mes_fato" text,
  "analise_franquia_fipe_grupo_grupo" text,
  "analise_franquia_fipe_grupo_tipo_franquia" text,
  "analise_franquia_fipe_grupo_franquia_numero" text,
  "analise_franquia_fipe_grupo_franquia_valor" text,
  "analise_cobertura_sinistro_data_fato" text,
  "analise_cobertura_sinistro_hora_fato" text,
  "analise_cobertura_sinistro_dia_semana" text,
  "analise_cobertura_sinistro_data_registro_bo" text,
  "analise_cobertura_sinistro_hora_registro_bo" text,
  "analise_cobertura_sinistro_numero_bo" text,
  "analise_cobertura_sinistro_tipo_bo" text,
  "analise_cobertura_sinistro_analise_financeira_vencimento_erp" text,
  "analise_cobertura_sinistro_analise_financeira_data_pagamento" text,
  "analise_cobertura_sinistro_analise_financeira_tipo" text,
  "analise_cobertura_sinistro_analise_financeira_esta_coberto" text,
  "analise_cobertura_sinistro_assistencia_24hrs" text,
  "consulta_detran_cnh_status" text,
  "consulta_detran_cnh_categoria" text,
  "consulta_detran_cnh_obs" text,
  "consulta_detran_cnh_validade" text,
  "consulta_detran_cnh_pontos" text,
  "consulta_detran_detalhamento_restricao_cnh" text,
  "consulta_detran_crlv_ano" text,
  "consulta_detran_ipva_licenciamento" text,
  "consulta_detran_multas" text,
  "consulta_detran_uf" text,
  "consulta_detran_multa_sinistro" text,
  "consulta_detran_restricoes" text,
  "analise_detalhamento_sinistro_local_fato_url" text,
  "analise_detalhamento_sinistro_relato_fato_bo" text,
  "analise_detalhamento_sinistro_item_regulamento_segurado" text,
  "analise_detalhamento_sinistro_art_ctb" text,
  "analise_detalhamento_sinistro_solicitado_sindicancia_pericia" text,
  "analise_detalhamento_sinistro_responsavel_sindicancia" text,
  "analise_detalhamento_sinistro_resultado_sindicancia" text,
  "analise_detalhamento_sinistro_pontos_exaltar_analista" text,
  "analise_detalhamento_sinistro_resumo_fato" text,
  "analise_detalhamento_sinistro_parecer_regulagem" text,
  "conclusao_analise_conclusao_segurado" text,
  "conclusao_analise_danos_veiculo_segurado" text,
  "conclusao_analise_classificacao_no_fato" text,
  "conclusao_analise_monta" text,
  "conclusao_analise_analista_responsavel" text,
  "conclusao_analise_inicio_analise" text,
  "conclusao_analise_conclusao_analise" text,
  "conclusao_analise_sinistro_aberto_em" text,
  "conclusao_analise_analise_recebida_em" text,
  "conclusao_analise_analise_liberada_em" text,
  "conclusao_analise_observacoes" text
);

-- indices para filtro/ordenacao
create index if not exists loovi_res_analista_ano_idx on public.loovi_ressarcimento (analista_tab, ano);
create index if not exists loovi_res_placa_idx on public.loovi_ressarcimento using gin ("identificacao_envolvidos_placa_segurado" gin_trgm_ops);

-- RLS: leitura publica (anon + authenticated), sem escrita
alter table public.loovi_ressarcimento enable row level security;
create policy "loovi_public_read" on public.loovi_ressarcimento for select to anon, authenticated using (true);
